# Generated by Django 3.1.5 on 2021-01-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='recipient_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
