# Generated by Django 3.1.5 on 2021-01-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210126_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='recipient_email',
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('recipient_email', models.CharField(blank=True, default='', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift', to='api.customer')),
            ],
        ),
    ]
