# Generated by Django 3.1.5 on 2021-01-27 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210126_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='api.customer'),
        ),
    ]
